### ISSUE TITLE
incompatibility of multiple footnotes between KOMA and scr

### ISSUE THREAD

**Issue by Glottotopia** [langsci/latex#11]
We use two ways of dealing with multiple footnotes at the same time. This should not be done because of incompatibilities. 

----
from log:
```txt
Class scrbook Warning: Change of `\@footnotemark' detected!
(scrbook)              Use of `footnotes=multiple' may break
(scrbook)              another package!
(scrbook)              Maybe you should remove the usage of
(scrbook)              option `footnotes=multiple' on input line 771.
```
----
from cls
```latex
\LoadClass[
	fontsize=\lsFontsize, % default is 11pt
        footnotes=multiple,
        numbers=noenddot,		% no point after last number of chapters/sections
        toc=bibliographynumbered,
        index=totoc,
	%draft=yes,
	]{scrbook}
...

\KOMAoptions{footnotes=multiple}
```
----
Apparently, this can create problems

For some options on how to solve this, see here
http://tex.stackexchange.com/questions/40072/incompatibility-between-footmisc-option-multiple-and-hyperref/62091#62091

**Comment by timmli** [comment]
For some reason, this warning does not appear anymore.
