### ISSUE TITLE
add paragraph numbering

### ISSUE THREAD

**Issue by timmli** [langsci/latex#18]

**Comment by timmli** [comment]
TeX provides the \everypar command, but it's unsafe to rely on it:
http://tex.stackexchange.com/questions/10513/automatically-assign-a-number-to-every-paragraph
Other solutions, except for manual ones, don't seem to be in sight.

**Comment by Glottotopia** [comment]
maybe line numbering as in https://www.overleaf.com/4388095vbckzh#/13083153/ ? Potentially only every 10 lines or so do avoid clutter

**Comment by Glottotopia** [comment]
we do not pursue epub anymore, hence we do not have the need for paragraph numbering for citation purposes
