### ISSUE TITLE
avoid option clash with todonotes 

### ISSUE THREAD

**Issue by timmli** [langsci/latex#20]
The package todonotes is used by the showindex option. The class should check whether it is already included.

**Comment by Glottotopia** [comment]
note that todonotes use marginpar. Marginpar in footnotes causes the dreaded "floats lost" error, which will inevitably confuse everybody with less than 10 yrs of Latex experience.

in the current setup, activating the showindex option will lead to the "floats lost" error as soon as there is one indexed term in a footnote.

**Comment by Glottotopia** [comment]
it would probably be OK to load todonotes in the class itself. It is an integral part of the workflow, so we can promote it from optional to integrated

**Comment by timmli** [comment]
@Glottotopia wrote:
> Marginpar in footnotes causes the dreaded "floats lost" error

That's why  `\marginpar` has gotten redefined with `\marginnote`.

I've also replaced` \usepackage` with `\RequirePackage` and glued the `textwidth` option to the `showindex` notes individually. Should be safer now.

Note that, as is, only `\isi` and `\is` are supported by `showindex`.
