### ISSUE TITLE
provide \lsAdditionalFonts to show extra fonts in the imprint

### ISSUE THREAD

**Issue by timmli** [langsci/latex#21]

**Comment by timmli** [comment]
\lsAdditionalFontsImprint created

**Comment by Glottotopia** [comment]
concatenation of font names should use commas and spaces. Currently, extra fonts are added to the last regular font without any mark of separation
On 25.11.2015 20:19, Timm Lichte wrote:
> \lsAdditionalFontsImprint created
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/langsci/latex/issues/21#issuecomment-159705772
>

-- 
Sebastian Nordhoff
Coordinator
Language Science Press
http://langsci-press.org/
sebastian.nordhoff@langsci-press.org
@LangSciPress
Habelschwerdter Allee 45
Room JK 28-106
14195 Berlin

**Comment by timmli** [comment]
Right now you have to fill in commas and spaces at the right place yourself:
`\renewcommand{\lsAdditionalFontsImprint}{, Font3, Font4}`. Is this a severe problem?

**Comment by Glottotopia** [comment]
this is the workaround I use. It is now big problem, but still rather 
ugly. No need to spend hours on this, but the issue should be recorded
S


On 30.11.2015 14:35, Timm Lichte wrote:
> Right now you have to fill in commas and spaces at the right place yourself:
> `\renewcommand{\lsAdditionalFontsImprint}{, Font3, Font4}`. Is this a severe problem?
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/langsci/latex/issues/21#issuecomment-160627821
>

-- 
Sebastian Nordhoff
Coordinator
Language Science Press
http://langsci-press.org/
sebastian.nordhoff@langsci-press.org
@LangSciPress
Habelschwerdter Allee 45
Room JK 28-106
14195 Berlin

**Comment by timmli** [comment]
There is a new command `\AdditionalFontImprint`.
You can use it like this `\AdditionalFontImprint{FontA} \AdditionalFontImprint{FontB}` or like this `\AdditionalFontImprint{FontA, FontB}`.
