### ISSUE TITLE
Shrink  didyoulikethisbook.pdf

### ISSUE THREAD

**Issue by timmli** [langsci/latex#27]
103 KB is too much.

**Comment by Glottotopia** [comment]
this is simply the cover page of a dummy book extracted with pdftk. Any idea why it would be that large?

**Comment by timmli** [comment]
What is the size of the source PDF?
Probably `xelatex` does not give optimal results wrt. file size. You could try 
1.  `latex+dvips+ps2pdf`  (I know this is difficult ;-)
2.  Adobe Acrobat

**Comment by Glottotopia** [comment]
reduced to 16k with 
`pdftk didyoulikethisbook.pdf cat 1 output c.pdf compress `
