### ISSUE TITLE
Clean up styles dir; remove less frequently required packages

### ISSUE THREAD

**Issue by Glottotopia** [langsci/latex#28]
I suggest we remove the following packages from our distribtuion @stefan11 @timmli :

- avm
- cgloss
- cglossx
- lsp-german
- lsp-macros

There is no need to duplicate the avm package.

We have lsp-cgloss, so cgloss and cglossx are not needed and confusing

lsp-german seems strange to have. We might keep it, but then we should also provide lsp-french. 

lsp-macros is now split into lsp-basic and lsp-optional

**Comment by timmli** [comment]
Done with one exception: `avm.sty`. It is not part of CTAN and there was an upgrade recently.

Regarding `langsci-german.sty`, see issue #19 .
