### ISSUE TITLE
LSP -> Langsci

### ISSUE THREAD

**Issue by Glottotopia** [langsci/latex#32]
Directory should be called 'Langsci'. Styles should be called 'langsci-somename.sty'

We want to avoid the TLA LSP.

**Comment by timmli** [comment]
or rather call the directory `langsci` (without capital L)?

**Comment by timmli** [comment]
I've renamed `LSP` to `langsci`, removed the `lsp-` prefix from directories and renamed `langsci.cls` to `langscibook.cls` in order to have different names for directory and class.
