### ISSUE TITLE
Remove langsci-colors.sty?

### ISSUE THREAD

**Issue by timmli** [langsci/latex#34]
It is included in `langscibook.cls`, but the colors are nowhere really used.
Colors are also defined in `series.def`.

**Comment by Glottotopia** [comment]
On 01/16/2016 09:20 PM, Timm Lichte wrote:
> It is included in `langscibook.cls`, but the colors are nowhere really used.
> Colors are also defined in `series.def`.

the reason for having a separate color definition is that these colors
are also used in beamer presentations and the flyers

> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/langsci/latex/issues/34
> 


-- 
Sebastian Nordhoff
Coordinator
Language Science Press
http://www.langsci-press.org
sebastian.nordhoff@langsci-press.org
@LangSciPress
Habelschwerdter Allee 45
Room JK 28-105
14195 Berlin

**Comment by timmli** [comment]
So, strictly speaking, we don't need them in the book class. But they are included for some reason in line 1467.

**Comment by Glottotopia** [comment]
It would probably be OK for the presentation template and the flyers to use series.def as well. Or have both series.def and colors.def, which looks a  bit cleaner to me since some elements, like the rainbow top bar, are independent of series but still use the colors.

**Comment by timmli** [comment]
`langsci-colors.sty` is replaced by `colors.def` in the seriesinfo directory. `colors.def` can be also used in flyers etc.
