### ISSUE TITLE
FreeMono obsolete?

### ISSUE THREAD

**Issue by timmli** [langsci/latex#37]
takes >1MB space and I don't see where it could be useful 
(@Glottotopia, @crysmann)

**Comment by Glottotopia** [comment]
+1

**Comment by Glottotopia** [comment]
There is only one book in the pipeline which uses a lot of \texttt, but it has not neared the typesetting phase, so I think that there will be no problem in a complete switch to DejaVu

**Comment by timmli** [comment]
I've removed FreeMono.
