### ISSUE TITLE
Title page of papers in collections broken

### ISSUE THREAD

**Issue by stefan11** [langsci/latex#48]
When I latex a volume with collected papers "Chapter 1" is printed on top of the paper title. This happens with texlive 2015, but does not happen with texlive 2013.

**Comment by kopeckyf** [comment]
This issue was also reported by a user working on a labphon book. It seems to not occur with TeX Live 2014 and 2016. Is 2016 already available on your OS?

**Comment by timmli** [comment]
@stefan11 Does this issue still exist?

**Comment by Glottotopia** [comment]
This issue is cause by negative vspace for chaptertitles in collections. This does not put the chapternumber a bit higher, but the chaptertitle, causing it to overlap with the chapter number
