### ISSUE TITLE
Long URLs in List of References

### ISSUE THREAD

**Issue by kopeckyf** [langsci/latex#51]
A long URL can cause the BibTeX compiler to fail. 

E.g. `http://www.academia.edu/3889487/An_Outline_Sketch_of_Gemzek_Grammar_draft`

will cause
```
    \verb
  http://www.academia.edu/3889487/An_Outline_Sketch_of_Gemzek_Grammar_dra
    \verb ft
```
Usually, only one `\verb` is called within `\entry`. Two `\verb` are not expected and cause the compiler to fail. 

Possible solution: Shorten URLs, e.g. by omitting the often unnecessary "www."
However this may not work with all web servers.

**Comment by Glottotopia** [comment]
putting `\verb` and  `http:...` on the same line will remedy this IIRC.
A workaround would be to remove the newline following a simple `\verb`
with sed in the Makefile. Note that removing newlines with sed is not
completely trivial

**Comment by Glottotopia** [comment]
The following code solves this problem. The issues is fixed upstream. Future versions of texlive should not produce this error
```
\makeatletter
\def\blx@maxline{77}
\makeatother
```
