### ISSUE TITLE
latest texlive requires language to be set

### ISSUE THREAD

**Issue by Glottotopia** [langsci/latex#52]
This means we either need to load babel or polyglossia somewhere. I have used `\usepackage[english]{babel}` for a start, but other options are conceivable as well. What does @timmli think?

**Comment by timmli** [comment]
I'd vote for an additional class option `language` that triggers the relevant commands.

**Comment by Glottotopia** [comment]
babel is now loaded by default with the language `english`. To use another language or additional language, use the package option `nobabel` and load your language support manually.
