### ISSUE TITLE
YYYYa in bibliographical entry in chapter footer

### ISSUE THREAD

**Issue by Glottotopia** [langsci/latex#53]
Chapters in edited volumes have a footer which indicates how the chapter should be cited. This citation is generated via bibtex.
If the author of a chapter has an other work in the list of references, the years will be disambiguated by a,b,c after the year. 
This leads to YYYYa showing up in the chapter footer and YYYYb showing up in the list of references. In both cases, however, only YYYY should show up. 

If there were two additional citations, these should show up as YYYYa and YYYYb in the list of references. The citation in the footer should still have a bare year. 

See the Jerro chapter in http://langsci-press.org/catalog/book/121 for an example.

**Comment by timmli** [comment]
The above commit fixes the issue in my toy example. Please check on a real project, e.g. http://langsci-press.org/catalog/book/121.

**Comment by Glottotopia** [comment]
confirmed. Good job!
