### ISSUE TITLE
latex-skeletons fails with TeX Live 2017

### ISSUE THREAD

**Issue by alenawitzlack** [langsci/latex#58]
```
(./langsci/bst/biblatex-langsci-unified.bbx

! Package xkeyval Error: no value specified for key `labeldate'.

See the xkeyval package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.8 ...bbreviate,dateabbrev=false,useprefix=false}
```

See https://tex.stackexchange.com/questions/330382/why-do-i-get-the-error-package-keyval-error-no-value-specified-for-labeldate

**Comment by timmli** [comment]
Thanks! Should be fixed now, at least in this repository. If you're addressing the skeletons, which belong to a different repository, you should commit an issue there: https://github.com/langsci/latex-skeletons/issues
