### ISSUE TITLE
A5 versions for kindle readers?

### ISSUE THREAD

**Issue by HedvigS** [langsci/latex#61]
Would it be possible to also derive a possibly slightly less well formatted a5 version of langscipress publications, for kindle readers?

I realise a lot more needs to be done to do it properly, figures etc, but a simple mod just to A5 would still be really handy :)!

**Comment by timmli** [comment]
The page margins of LangSci books are quite large, so the print area has roughly A5 size. 
I don't know the PDF viewer in kindle, but maybe there is a fit-to-content zoom? I know some PDF viewers that can do this (e.g. SumatraPDF).

**Comment by Glottotopia** [comment]
formatting is really tough for linguistics books, and it will not be possible to do it for more than one paper size
