### ISSUE TITLE
decapitalization does not work for techreports

### ISSUE THREAD

**Issue by stefan11** [langsci/latex#69]
Title is not decapitalized. See also https://github.com/langsci/hoehle/issues/197

@techreport{Meurers2000,
	Author = {Meurers, Walt Detmar},
	institution = {Universität Stuttgart/""Universit{\"a}t T{\"u}bingen},
	type = {Arbeitspapiere des Sonderforschungsbereichs 340, Bericht Nr.\,145},
	Title = {Lexical Generalizations in the Syntax of {German} Non-Finite Constructions},
	Year = {2000}}

**Comment by timmli** [comment]
biblatex-sp-unified does not support biblatex types `techreport` (a subtype of `report`) and `misc`. My guess is that `techreport` is supposed to be treated as `book` or `article`, while `misc` would fall under `unpublished`. Anyway, sentence case can be activated with

    \DeclareFieldFormat[techreport,report,misc]{titlecase}{\MakeSentenceCase*{#1}}%

Fixed in commit 520b2ea.
