### ISSUE TITLE
\citep* does not work

### ISSUE THREAD

**Issue by stefan11** [langsci/latex#75]
It should display all authors, but it does display none of them:

![bildschirmfoto 2018-01-11 um 12 39 42](https://user-images.githubusercontent.com/4655859/34823879-86237f8e-f6cc-11e7-9608-d81f68e526e9.png)

This is a MWE:
```latex
\documentclass[output=paper
  ,modfonts
  ,nonflat]{langsci/langscibook}

\usepackage{filecontents}


\begin{filecontents}{SM.bib}
@article{BPYC2011a,
	Author = {Robert C. Berwick and Paul Pietroski and Beracah Yankama and Noam Chomsky},
	Journal = {Cognitive Science},
	Number = {7},
	Pages = {1207--1242},
	Title = {{Poverty of the Stimulus} Revisited},
	Volume = {35},
	Year = {2011}}
\end{filecontents}

\bibliography{SM}

\title{Doing bibliographies with the stars}

\begin{document}

\citep*{BPYC2011a} haben gezeigt, dass \ldots.


\printbibliography[heading=subbibliography,notkeyword=this]
\end{document}
```

**Comment by stefan11** [comment]
Even more minimal:
```latex
\documentclass{scrbook}

\usepackage[natbib,
style=biblatex-sp-unified,
citestyle=sp-authoryear-comp
]{biblatex}

\usepackage{filecontents}


\begin{filecontents}{SM.bib}
@article{BPYC2011a,
	Author = {Robert C. Berwick and Paul Pietroski and Beracah Yankama and Noam Chomsky},
	Journal = {Cognitive Science},
	Number = {7},
	Pages = {1207--1242},
	Title = {{Poverty of the Stimulus} Revisited},
	Volume = {35},
	Year = {2011}}
\end{filecontents}

\bibliography{SM}

\title{Doing bibliographies with the stars}

\begin{document}

\citep{BPYC2011a} haben gezeigt, dass \ldots.

\citep*{BPYC2011a} haben gezeigt, dass \ldots.

\printbibliography[heading=subbibliography,notkeyword=this]
\end{document}
```

**Comment by timmli** [comment]
Maybe that's due to an [issue](https://github.com/plk/biblatex/issues/354) with `biblatex`, but it seems to be solved.

Anyway, you could instead use: `\AtEveryCitekey{\ifciteseen{}{\defcounter{maxnames}{999}}}` 
This does what you presumably want (show all names in the first citation) automatically. Be sure to activate the cite tracker (`citetracker=true`) when loading `biblatex` in the class.

**Comment by stefan11** [comment]
@timmli No, I do not want "name everything at first occurrence". I want "Stefan tells you what to do". (Or rather LangSci writer tells you what to do.) `\citep*` is supposed to list all names `(Chomsky, Berwick & Hauser, 2014)`. This is what it did with bibtex and the natbib package loaded.

Shall I update the biblatex package? I am afraid of doing this. I once updated all packages from texlive 2017 and then the langsci class stopped working. I had to reinstall texlive.

**Comment by timmli** [comment]
I have Biblatex 3.7 installed (as part of TeXLive 2016) and the same problem with `\citep*`. The most recent version is 3.10. Not sure whether an update solves this.

The original definition of `\citep` is this:

```latex
\newrobustcmd*{\citep}{%
  \@ifstar
    {\AtNextCite{\AtEachCitekey{\defcounter{maxnames}{999}}}%
     \parencite}
    {\parencite}
```}

So you could define an ad hoc command `\citepall` like this:

```latex
\newrobustcmd*{\citepall}{%
  \AtNextCite{\AtEachCitekey{\defcounter{maxnames}{999}}}%
  \parencite}
```

This strangely works.

**Comment by stefan11** [comment]
Update hilft nicht. \\citepall funktioniert. Irgendwas zerschießt das \\citep*. Hm.

**Comment by stefan11** [comment]
Das kriege ich, wenn ich biber und biblatex über ctan update:

! Missing number, treated as zero.
<to be read again> 
                   \global 
l.1569 ...r{Herling1821T,Herling1828,Herling1830} 
                                                  oder schon bei \citet{Adel...

? 

Dann installier ich jetzt mal texlive neu ...

**Comment by stefan11** [comment]
The natbib compatibility code is loaded by biblatex (blx-natbib.def) but somehow is not effective. I redeclared the commands in our class and it works. This should be cleaned up one day ...

**Comment by moewew** [comment]
In case you are wondering, this is due to `sp-authoryear-comp.cbx`'s redefining `\citep`, in particular https://github.com/semprag/biblatex-sp-unified/blob/dc96bb703a018b0b3a2886d14a54ccb58052044a/cbx/sp-authoryear-comp.cbx#L302

The `natbib` compatibility configuration is always loaded before the bibliography and citation styles, and so its definitions are overwritten if a `.cbx` or `.bbx` file defines things differently.

**Comment by stefan11** [comment]
@moewew Ah, thanks. It was completely mysterious for me. Then maybe my redefinition of the redefinition is problematic. Somebody should tell sem-prag to fix their redefinition.

**Comment by kopeckyf** [comment]
Related: https://github.com/langsci/langscibook/commit/a6e3f56ce312ddf7ee423ce1185e6df9057bc0ed

(This commit removes all the definitions and delegates the work to `[natbib=true]` option from `biblatex`.)
